### ISSUE TITLE
PlotUtil missing

### ISSUE THREAD

**Issue by tracek** [PacktPublishing/Deep-Learning-with-Hadoop#1]
In the [MLPClassifierSaturn](https://github.com/PacktPublishing/Deep-Learning-with-Hadoop/blob/master/Chapter02/MLPClassifierSaturn.java#L125) you are using PlotUtil, but the class is nowhere to be found. Can you please include it?

**Comment by shubham763** [comment]
Please reopen if the issue still persists.
